@Hostname = http://localhost:5271/api

POST {{Hostname}}/Products
Content-Type: application/json
Accept: application/json

{
    "Name" : "chicken",
    "Price" : 888.45,
    "ManufactureDate" : "2026-06-07",
    "InStocks" : true,
    "Note" : "fresh and fresh"
}

GET {{Hostname}}/Products
Accept: application/json

GET {{Hostname}}/Products/1
Accept: application/json



###
